services:
  object-detection:
    build:
      context: ./object-detection-service
      dockerfile: Dockerfile
    container_name: object-detection
    ports:
      - "5005:5005"
    volumes:
      - ./sample_images:/app/sample_images
    restart: unless-stopped

  song-recommendation:
    build:
      context: ./song-recommendation-service
      dockerfile: Dockerfile
    container_name: song-recommendation
    ports:
      - "5003:5003"
    volumes:
      - ./turkish_song_lyrics.csv:/app/turkish_song_lyrics.csv
    restart: unless-stopped
